#pragma once
#include <functional>
#include <iostream>
#include <exception>
#include <list>
#include <vector>
#include <map>
#include <string>
#include <memory>
#include <mutex>
#include <thread>
#include <chrono>
#include <ratio>
#include <cassert>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <ctime>